### PR TITLE
Add mastodon support

### PR DESCRIPTION
**Pull request by schochastics**
I have added a shortcode to embed mastodon post. I think I also updated all examples and the README

### CODE REVIEW

**Comment by sellorm** [comment]
Thanks for this @schochastics, 
This is a really exciting addition. How you you feel about this shortcode using the full URL to the toot/post though?

Like this:

```
{{< mastodon https://mastodon.instance/@username/12345678909 >}}
```

I feel like this would make it easier for the user as they wouldn't need to think about how they break up the URL that they already have.

I know this is probably slightly inconsistent with some of the existing shortcodes in this extension, but they're mostly the way they are for backward compatibility with Hugo.

What do you think?

**Comment by schochastics** [comment]
@sellorm I actually wanted to implement it like this but thought for consistency with the other shortcodes, I separate the components. I will change it since I also think that it is easier to use with the full URL

**Comment by schochastics** [comment]
Done but I am confused about how the code works. Although The input is only one url, I still needed to parse two input arguments(???). Maybe you have an idea whats going on

**Review by sellorm — APPROVED** [review]
I've removed that two-inputs requirement from the function, so it should work fine now.

**Comment by sellorm** [comment]
Thanks so much for this, @schochastics!

**Pull request merged**
